#Requires AutoHotkey v2.0

#Include BankDeposit.ahk
#Include Borbventure.ahk
#Include Cards.ahk
#Include CardsBuy.ahk
#Include Claw.ahk
#Include Converters.ahk
#Include CursedCheese.ahk
#Include DailyGems.ahk
#Include FarmGFSS.ahk
#Include FarmNatureBoss.ahk
#Include FarmNormalBoss.ahk
#Include Fishing.ahk
#Include FishingChallenge.ahk
#Include FishingTourney.ahk
#Include GemFarm.ahk
#Include Harbor.ahk
#Include NatureHyacinth.ahk
#Include Prestiges.ahk
#Include Pub.ahk
#Include Pyramid.ahk
#Include TowerTimeWarp.ahk
#Include TowerFarmPassive.ahk
#Include LeaftonTaxi.ahk
#Include MineMaintainer.ahk
#Include SuitcaseSpam.ahk
#Include QuickPrestige.ahk
#Include ShadowCrystalFight.ahk