#Requires AutoHotkey v2.0 



#Include Mines.ahk


#include zAstralOasis.ahk
#include zBiotiteForest.ahk
#include zBlackLeafHole.ahk
#include zBlackPlanetEdge.ahk
#include zBluePlanetEdge.ahk
#include zButterflyField.ahk
#include zCursedKokkaupunki.ahk
#Include zCursedHalloween.ahk
#include zDiceyMeadows.ahk
#include zDimensionalTapestry.ahk
#include zEnergyShrine.ahk
#include zEnergySingularity.ahk
#include zFarmField.ahk
#include zFireFieldsPortal.ahk
#include zFireUniverse.ahk
#include zFlameBrazier.ahk
#include zGlintingThicket.ahk
#include zGreenPlanetEdge.ahk
#include zHomeGarden.ahk
#include zKokkaupunki.ahk
#include zLeafsinkHarbor.ahk
#include zMountMoltenfurty.ahk
#include zMountain.ahk
#include zNeighborsGarden.ahk
#include zPlanckScope.ahk
#include zPlasmaForest.ahk
#include zPrimordialEthos.ahk
#include zPurplePlanetEdge.ahk
#include zQuantumAether.ahk
#include zQuarkNexus.ahk
#include zQuarkPortal.ahk
#include zRedPlanetEdge.ahk
#include zSoulCrypt.ahk
#include zSoulForge.ahk
#include zSoulPortal.ahk
#include zSoulTemple.ahk
#include zSpace.ahk
#include zSparkBubble.ahk
#include zSparkPortal.ahk
#include zSparkRange.ahk
#include zTHEVOID.ahk
#include zTerrorGraveyard.ahk
#include zTheAbandonedResearchStation.ahk
#include zTheAbyss.ahk
#include zTheAncientSanctum.ahk
#include zTheCelestialPlane.ahk
#include zTheCheesePub.ahk
#include zTheCoalMine.ahk
#include zTheCursedPyramid.ahk
#include zTheDarkGlade.ahk
#include zTheDoomedTree.ahk
#include zTheExaltedBridge.ahk
#include zTheFabricoftheLeafverse.ahk
#include zTheFireTemple.ahk
#include zTheHiddenSea.ahk
#include zTheHollow.ahk
#Include zTheInfernalDesert.ahk
#include zTheInnerCursedPyramid.ahk
#include zTheLeafTower.ahk
#include zTheLoneTree.ahk
#include zTheMoon.ahk
#include zTheMythicalGarden.ahk
#include zTheShadowCavern.ahk
#include zTheVolcano.ahk
#include zVialofLife.ahk
#include zVilewoodCemetery.ahk
#include zYourHouse.ahk