#Requires AutoHotkey v2.0


#Include Mines.ahk

#include cZoneCards.ahk

#Include zAnteLeafton.ahk
#Include zAstralOasis.ahk
#Include zBiotiteForest.ahk
#Include zBlackLeafHole.ahk
#Include zBlackPlanetEdge.ahk
#Include zBluePlanetEdge.ahk
#Include zButterflyField.ahk
#Include zCursedKokkaupunki.ahk
#Include zCursedHalloween.ahk
#Include zDiceyMeadows.ahk
#Include zDimensionalTapestry.ahk
#Include zEnergyShrine.ahk
#Include zEnergySingularity.ahk
#Include zFarmField.ahk
#Include zFireFieldsPortal.ahk
#Include zFireUniverse.ahk
#Include zFlameBrazier.ahk
#Include zGlintingThicket.ahk
#Include zGreenPlanetEdge.ahk
#Include zHomeGarden.ahk
#Include zKokkaupunki.ahk
#Include zLeafsinkHarbor.ahk
#Include zMountMoltenfurty.ahk
#Include zMountain.ahk
#Include zNeighborsGarden.ahk
#Include zPlanckScope.ahk
#Include zPlasmaForest.ahk
#Include zPrimordialEthos.ahk
#Include zPurplePlanetEdge.ahk
#Include zQuantumAether.ahk
#Include zQuarkNexus.ahk
#Include zQuarkPortal.ahk
#Include zRedPlanetEdge.ahk
#Include zSoulCrypt.ahk
#Include zSoulForge.ahk
#Include zSoulPortal.ahk
#Include zSoulTemple.ahk
#Include zSpace.ahk
#Include zSparkBubble.ahk
#Include zSparkPortal.ahk
#Include zSparkRange.ahk
#Include zTHEVOID.ahk
#Include zTerrorGraveyard.ahk
#Include zTheAbandonedResearchStation.ahk
#Include zTheAbyss.ahk
#Include zTheAncientSanctum.ahk
#Include zTheCelestialPlane.ahk
#Include zTheCheesePub.ahk
#Include zTheCoalMine.ahk
#Include zTheCursedPyramid.ahk
#Include zTheDarkGlade.ahk
#Include zTheDoomedTree.ahk
#Include zTheExaltedBridge.ahk
#Include zTheFabricoftheLeafverse.ahk
#Include zTheFireTemple.ahk
#Include zTheHiddenSea.ahk
#Include zTheHollow.ahk
#Include zTheInfernalDesert.ahk
#Include zTheInnerCursedPyramid.ahk
#Include zTheLeafTower.ahk
#Include zTheLoneTree.ahk
#Include zTheMoon.ahk
#Include zTheMythicalGarden.ahk
#Include zTheShadowCavern.ahk
#Include zTheVolcano.ahk
#Include zVialofLife.ahk
#Include zVilewoodCemetery.ahk
#Include zYourHouse.ahk